services:
  app:
    build:
      target: dev
    environment:
      PHP_IDE_CONFIG: "serverName=stage"
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    ports:
      - "8088:80"

  mysql:
    restart: unless-stopped
    ports:
      - "3313:3306"

  redis:
    restart: unless-stopped
    ports:
      - "6383:6379"
